### ISSUE TITLE
Error parsing some metrics on Sybase 16.0

### ISSUE THREAD

**Issue by nlamirault** [ncabatoff/dbms_exporter#5]
Hi,

i try to retrieve Sybase metrics using this [Docker image](https://hub.docker.com/r/datagrip/sybase/) v16.0

```bash
$ docker run -d -t -p 5000:5000 -e "SYBASE_USER=guest" -h dksybase --name sybase157 datagrip/sybase:16.0
```

Using the exporter : 

```
$ DATA_SOURCE_NAME="compatibility_mode=sybase;user=guest;pwd=guest1234;server=0.0.0.0:5000" ./dbms_exporter -driver sybase -queryfile sybase
.yaml -log.level debug
DEBU[0000] opening freetds connection                    source=db.go:140
DEBU[0000] Querying namespace:  sybase_spid_count_by_user  source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT l.name AS dbuser, count(*) AS conns FROM master.dbo.sysprocesses p, master.dbo.syslogins l WHERE p.suid = l.suid GROUP BY l.name  source=recipes.go:92                             
DEBU[0000] got results [{[dbuser conns] [[guest 1]]}]    source=recipes.go:97                                                                                                                                      
DEBU[0000] handling resultset 0 with 1 rows              source=dbms_exporter.go:344                                                                                                                               
DEBU[0000] Querying namespace:  sybase_spid_count_blocked_by_user  source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT l.name AS dbuser, count(*) AS conns FROM master.dbo.sysprocesses p, master.dbo.syslogins l WHERE p.suid = l.suid AND blocked != 0 GROUP BY l.name  source=recipes.go:92            
DEBU[0000] got results [{[dbuser conns] []}]             source=recipes.go:97
DEBU[0000] handling resultset 0 with 0 rows              source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_dbsize            source=dbms_exporter.go:334
DEBU[0000] running SQL:  USE master                      source=recipes.go:92                                                                                                                                      
DEBU[0000] got results []                                source=recipes.go:97                                                                                                                                      
DEBU[0000] running SQL:  sp_helpdb tempdb                source=recipes.go:92
DEBU[0000] got results [{[name db_size owner dbid created durability lobcomplvl inrowlen status] [[tempdb      348.0 MB sa    2 Apr 18, 2019 no_recovery          0     NULL select into/bulkcopy/pllsort, trunc log
 on chkpt, mixed log and data, allow wide dol rows]]} {[device_fragments size usage created free_kbytes] [[master       24.0 MB data and log Nov 17 2016  9:54AM            10336] [tempdbdev      324.0 MB data and
 log Nov 17 2016  9:56AM           330256]]}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 1 rows              source=dbms_exporter.go:344
DEBU[0000] handling resultset 1 with 2 rows              source=dbms_exporter.go:344
INFO[0000] Could not parse string: strconv.ParseFloat: parsing "      24.0 MB": invalid syntax  source=db.go:157
ERRO[0000] Unexpected error parsing column:  sybase_dbsize size       24.0 MB  source=dbms_exporter.go:388
DEBU[0000] unknown metric "created" in namespace "sybase_dbsize", labels: [master data and log]  source=dbms_exporter.go:395
INFO[0000] Could not parse string: strconv.ParseFloat: parsing "Nov 17 2016  9:54AM": invalid syntax  source=db.go:157
WARN[0000] Unparseable column type - discarding:  sybase_dbsize created  source=dbms_exporter.go:403
INFO[0000] Could not parse string: strconv.ParseFloat: parsing "           10336": invalid syntax  source=db.go:157
ERRO[0000] Unexpected error parsing column:  sybase_dbsize free_kbytes            10336  source=dbms_exporter.go:388
INFO[0000] Could not parse string: strconv.ParseFloat: parsing "     324.0 MB": invalid syntax  source=db.go:157
ERRO[0000] Unexpected error parsing column:  sybase_dbsize size      324.0 MB  source=dbms_exporter.go:388
DEBU[0000] unknown metric "created" in namespace "sybase_dbsize", labels: [tempdbdev data and log]  source=dbms_exporter.go:395
INFO[0000] Could not parse string: strconv.ParseFloat: parsing "Nov 17 2016  9:56AM": invalid syntax  source=db.go:157
WARN[0000] Unparseable column type - discarding:  sybase_dbsize created  source=dbms_exporter.go:403
INFO[0000] Could not parse string: strconv.ParseFloat: parsing "          330256": invalid syntax  source=db.go:157
ERRO[0000] Unexpected error parsing column:  sybase_dbsize free_kbytes           330256  source=dbms_exporter.go:388
DEBU[0000] Querying namespace:  sybase_spid_count_special_users  source=dbms_exporter.go:334
DEBU[0000] Querying namespace:  sybase_spid_count_special_users  source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT cmd AS sysproc, 1 AS conns FROM master.dbo.sysprocesses WHERE suid = 0  source=recipes.go:92
DEBU[0000] got results [{[sysproc conns] [[MEMORY TUNE 1] [DEADLOCK TUNE 1] [KPP HANDLER 1] [ASTC HANDLER 1] [CHECKPOINT SLEEP 1] [HK WASH 1] [HK GC 1] [HK CHORES 1] [PORT MANAGER 1] [NETWORK HANDLER 1] [LICENSE
HEARTBEAT 1]]}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 11 rows             source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_spid_count_by_status  source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT status, count(*) AS conns FROM master.dbo.sysprocesses GROUP BY status  source=recipes.go:92
DEBU[0000] got results [{[status conns] [[sleeping 11] [running 1]]}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 2 rows              source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_syslogshold       source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT d.name AS db_name, l.name AS dbuser, MAX(datediff(ss, starttime, getdate())) AS held_seconds FROM master.dbo.syslogshold h, master.dbo.sysdatabases d, master.dbo.sysprocesses p, ma
ster.dbo.syslogins l WHERE h.dbid=d.dbid AND h.spid = p.spid AND p.suid = l.suid GROUP BY d.name, l.name  source=recipes.go:92
DEBU[0000] got results [{[db_name dbuser held_seconds] []}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 0 rows              source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_config            source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT name, value FROM master.dbo.sysconfigures WHERE name IN ( 'number of user connections', 'time slice', 'procedure cache percent', 'number of open objects')  source=recipes.go:92
DEBU[0000] got results [{[name value] [[number of open objects 500] [number of user connections 25] [time slice 100]]}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 3 rows              source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_engines           source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT COUNT(*) AS running FROM master.dbo.sysengines  source=recipes.go:92
DEBU[0000] got results [{[running] [[1]]}]               source=recipes.go:97
DEBU[0000] handling resultset 0 with 1 rows              source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_kernel            source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT CONVERT(REAL, @@cpu_busy) * (CONVERT(REAL, @@timeticks) / 1000000) cpu_busy_seconds_total, CONVERT(REAL, @@idle) * (CONVERT(REAL, @@timeticks) / 1000000) cpu_idle_seconds_total, @@
connections connections, @@pack_received tcp_packets_received_total, @@pack_sent tcp_packets_sent_total, @@packet_errors tcp_packet_errors_total, @@total_read disk_reads_total, @@total_write disk_writes_total, @@
total_errors disk_errors_total  source=recipes.go:92
DEBU[0000] got results [{[cpu_busy_seconds_total cpu_idle_seconds_total connections tcp_packets_received_total tcp_packets_sent_total tcp_packet_errors_total disk_reads_total disk_writes_total disk_errors_total]
[[19.7 11.5 8 45 52 0 1177 322 0]]}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 1 rows              source=dbms_exporter.go:344
DEBU[0000] Querying namespace:  sybase_syslogins         source=dbms_exporter.go:334
DEBU[0000] running SQL:  SELECT name AS dbuser, totcpu, totio FROM master.dbo.syslogins  source=recipes.go:92
DEBU[0000] got results [{[dbuser totcpu totio] [[sa 192 104911] [probe 0 0] [guest 0 0]]}]  source=recipes.go:97
DEBU[0000] handling resultset 0 with 3 rows              source=dbms_exporter.go:344
INFO[0000] Starting Server: :9113                        source=dbms_exporter.go:505
```

Any idea how to fix that ?

**Comment by ncabatoff** [comment]
Hi @nlamirault ,

That's awesome that you found a freely available Sybase docker image!  I wonder if I can count on it sticking around long enough to depend on it for tests...

Anyway, it looks like the sp_helpdb output has changed since Sybase 11.  Unsurprising.  Try replacing the corresponding section of the sybase.yaml with something like this:

```
dbsize:
  queries: 
    # USE master is to protect us against some other query leaving us in
    # db tempdb; if you run sp_helpdb tempdb while in tempdb you get a bogus
    # third resultset which will break the parsing of the recipe results.
    - "USE master"
    - "sp_helpdb tempdb"
  resultsets:
    - discard:
    - metrics:
      - db_name:
          usage: "FIXED"
          description: "database name"
          value: "tempdb"
      - device_fragments:
          usage: "LABEL"
          description: "short device name"
      - size:
          usage: "GAUGE"
          regexp: "^\\s*([\\d.]+)\\s+MB$"
          description: "size in MB"
      - usage:
          usage: "LABEL"
          description: "data or log"
      - created:
          usage: "DISCARD"
      - durability:
          usage: "DISCARD"
      - inrowlen:
          usage: "GAUGE"
          description: "num rows"
      - "free kbytes":
          usage: "GAUGE"
          regexp: "^\\s*([\\d]+)$"
          description: "free space in KB"
```
